config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end
  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Warehouse App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1>Galpões e Estoque</h1>
      <% end %>
      
      <nav>
        <%= link_to 'Fornecedores', suppliers_path %> |
        <%= link_to 'Modelos de Produtos', product_models_path %> |
        <%= link_to 'Registrar Pedido', new_order_path %> |
        <%= link_to 'Meus Pedidos', orders_path %> |
        
        <% if user_signed_in? %>
          <%= form_with url: search_orders_path, method: :get do |f| %>
            <%= f.label :query, 'Buscar Pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar' %>
          <% end %>
          <%= current_user.description %> |
          <%= button_to 'Sair', destroy_user_session_path, method: :delete, class: 'link' %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path %>
        <% end %>
        
      </nav>
    </header>
    <main>
        <div>
          <%= alert %>
      </div>
        <div>
          <%= notice %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>